version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - INSTALL_GIT=true
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./public:/app/public
      - ./images.db:/app/images.db
    restart: unless-stopped
